/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiMessagesIdRouteImport } from './routes/api/messages.$id'
import { Route as ApiHistoryIdRouteImport } from './routes/api/history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesIdRoute = ApiMessagesIdRouteImport.update({
  id: '/api/messages/$id',
  path: '/api/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryIdRoute = ApiHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
  '/api/messages/$id': typeof ApiMessagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/chat': typeof ChatIndexRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
  '/api/messages/$id': typeof ApiMessagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
  '/api/messages/$id': typeof ApiMessagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/history'
    | '/chat/$id'
    | '/chat/'
    | '/api/history/$id'
    | '/api/messages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/history'
    | '/chat/$id'
    | '/chat'
    | '/api/history/$id'
    | '/api/messages/$id'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/history'
    | '/chat/$id'
    | '/chat/'
    | '/api/history/$id'
    | '/api/messages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHistoryRoute: typeof ApiHistoryRouteWithChildren
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiMessagesIdRoute: typeof ApiMessagesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/$id': {
      id: '/api/messages/$id'
      path: '/api/messages/$id'
      fullPath: '/api/messages/$id'
      preLoaderRoute: typeof ApiMessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/$id': {
      id: '/api/history/$id'
      path: '/$id'
      fullPath: '/api/history/$id'
      preLoaderRoute: typeof ApiHistoryIdRouteImport
      parentRoute: typeof ApiHistoryRoute
    }
  }
}

interface ApiHistoryRouteChildren {
  ApiHistoryIdRoute: typeof ApiHistoryIdRoute
}

const ApiHistoryRouteChildren: ApiHistoryRouteChildren = {
  ApiHistoryIdRoute: ApiHistoryIdRoute,
}

const ApiHistoryRouteWithChildren = ApiHistoryRoute._addFileChildren(
  ApiHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHistoryRoute: ApiHistoryRouteWithChildren,
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiMessagesIdRoute: ApiMessagesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
